Repository Keyz-EIP/Keyz, pull requests merged in 2025-06, with the labels that each got.

#22 Doc: update server documentation
  Code/Web/compose.yaml
  Code/update.sh
  Documentations/Technical/Server/architecture.md
  Documentations/Technical/Server/database.md
  Documentations/Technical/Server/install.md
  Documentations/Technical/Server/introduction.md
  Documentations/Technical/Server/prisma-erd.svg
  Documentations/Technical/Server/testing.md
  Documentations/Technical/deploy.md
Labels: docs, feature

#23 Picture number limit on requests in backend
  Code/Server/models/ai.go
  Code/Server/models/damage.go
  Code/Server/models/inventoryReport.go
Labels: feature

#24 Technical Doc : Global web architecture documentation
  Documentations/Technical/Diagram/architecture-diagram.jpg
  Documentations/Technical/Diagram/global-architecture.jpg
  Documentations/Technical/Web/API/index.md
  Documentations/Technical/Web/Architecture/architecture.md
  Documentations/Technical/Web/Architecture/components/.gitkeep
  Documentations/Technical/Web/Architecture/data-flows/data-flows.md
  Documentations/Technical/Web/Architecture/index.md
  Documentations/Technical/Web/Development/coding-standards.md
  Documentations/Technical/Web/Development/index.md
  Documentations/Technical/Web/Development/testing.md
  Documentations/Technical/Web/Features/authentication/auth-and-security.md
  Documentations/Technical/Web/Features/index.md
  Documentations/Technical/Web/Features/internationalization/translation.md
  Documentations/Technical/Web/Features/messages/messages.md
  Documentations/Technical/Web/Features/navigation/navigation-system.md
  Documentations/Technical/Web/Features/real-property/real-property.md
  Documentations/Technical/Web/Overview/getting-started.md
  Documentations/Technical/Web/Overview/global-overview.md
  Documentations/Technical/Web/Resources/Diagrams/Architecture/Web-architecture.jpg
  Documentations/Technical/Web/Resources/Diagrams/Data-flows/data-flow-authentication.jpg
  Documentations/Technical/Web/Resources/Diagrams/Data-flows/data-flow-property.jpg
  Documentations/Technical/Web/cache.md
  Documentations/Technical/Web/index.md
  Documentations/Technical/deploy.md
Labels: docs

#25 Feat/owner overview
  Code/Mobile_Android/app/src/main/java/com/example/keyz/apiCallerServices/DamageCallerService.kt
  Code/Mobile_Android/app/src/main/java/com/example/keyz/apiCallerServices/DashBoardCallerService.kt
  Code/Mobile_Android/app/src/main/java/com/example/keyz/apiClient/ApiService.kt
  Code/Mobile_Android/app/src/main/java/com/example/keyz/apiClient/mockApi/MockApiOutputValues.kt
  Code/Mobile_Android/app/src/main/java/com/example/keyz/apiClient/mockApi/MockedApiService.kt
  Code/Mobile_Android/app/src/main/java/com/example/keyz/dashboard/DashBoard.kt
  Code/Mobile_Android/app/src/main/java/com/example/keyz/dashboard/DashBoardViewModel.kt
  Code/Mobile_Android/app/src/main/res/values-fr/strings.xml
  Code/Mobile_Android/app/src/main/res/values/strings.xml
Labels: feature

#28 Feat/user web documentation real properties
  Documentations/User/Web/Images/addDocument.png
  Documentations/User/Web/Images/addRoom.png
  Documentations/User/Web/Images/createProperty.png
  Documentations/User/Web/Images/damagesTab.png
  Documentations/User/Web/Images/listProperties.png
  Documentations/User/Web/Images/propertyActions.png
  Documentations/User/Web/Pages/Real Properties/CreateProperty.md
  Documentations/User/Web/Pages/Real Properties/ListProperties.md
  Documentations/User/Web/Pages/Real Properties/PropertyActions.md
Labels: docs, feature

#30 Automatic redirection to login fail when now token in app
  Code/Mobile_iOS/Keyz/Sources/Components/ErrorNotificationView.swift
  Code/Mobile_iOS/Keyz/Sources/Resources/fr.lproj/Localizable.strings
  Code/Mobile_iOS/Keyz/Sources/TestImmotepApp.swift
  Code/Mobile_iOS/Keyz/Sources/Utils/AppDelegate.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryStuffView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/Managers/InventoryReportManager.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Login/LoginView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Messages/MessagesView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Overview/OverviewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Overview/OverviewView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Overview/OverviewViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/CreatePropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/EditPropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/OwnerPropertyViewModel.swift
Labels: bug

#35 Fix AI error handling
  Code/Server/controllers/ai.go
  Code/Server/services/chatgpt/chatgpt.go
Labels: bug

#37 Fix pdf generation crash
  Code/Server/controllers/inventoryReport.go
  Code/Server/docs/docs.go
  Code/Server/docs/swagger.json
  Code/Server/docs/swagger.yaml
  Code/Server/services/pdf/pdf.go
  Code/Server/utils/error.go
Labels: bug

#36 Refactor web norme and convention
  Code/Web/.eslintrc.cjs
  Code/Web/src/assets/images/EmptyImage.svg
  Code/Web/src/components/common/Badge/Badge.tsx
  Code/Web/src/components/common/Button/Button.tsx
  Code/Web/src/components/common/Card/Card.tsx
  Code/Web/src/components/common/Empty/Empty.tsx
  Code/Web/src/components/common/Input/Input.tsx
  Code/Web/src/components/common/Modal/Modal.tsx
  Code/Web/src/components/common/index.ts
  Code/Web/src/components/features/Damages/details/DetailsPart.tsx
  Code/Web/src/components/features/Overview/Widgets/OpenDamages/OpenDamages.tsx
  Code/Web/src/components/features/Overview/Widgets/Reminders/Reminders.tsx
  Code/Web/src/components/features/RealProperty/PropertyCard.module.css
  Code/Web/src/components/features/RealProperty/PropertyCard.tsx
  Code/Web/src/components/features/RealProperty/PropertyFilterCard.tsx
  Code/Web/src/components/features/RealProperty/PropertyForm/PropertyFormFields.tsx
  Code/Web/src/components/features/RealProperty/details/DetailsPart/DetailsPart.tsx
  Code/Web/src/components/features/RealProperty/details/DetailsPart/InviteTenantModal.tsx
  Code/Web/src/components/features/RealProperty/details/DetailsPart/PropertyHeader.tsx
  Code/Web/src/components/features/RealProperty/details/DetailsPart/PropertyImage.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Documents/DocumentList.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Documents/UploadForm.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/AddRoomModal.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/AddStuffModal.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/GridView.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/InventoryControls.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/ListView.css
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/ListView.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/PlanView.tsx
  Code/Web/src/components/ui/Loader/CardPropertyLoader.tsx
  Code/Web/src/interfaces/Property/Property.ts
  Code/Web/src/utils/types/roomTypes.ts
  Code/Web/src/views/Authentification/ForgotPassword/ForgotPassword.tsx
  Code/Web/src/views/Authentification/Login/Login.tsx
  Code/Web/src/views/Authentification/Register/Register.tsx
  Code/Web/src/views/Lost/Lost.tsx
  Code/Web/src/views/RealProperty/RealProperty.tsx
  Code/Web/src/views/RealProperty/create/RealPropertyCreate.tsx
  Code/Web/src/views/RealProperty/details/RealPropertyDetails.tsx
  Code/Web/src/views/RealProperty/details/tabs/1DocumentsTab.tsx
  Code/Web/src/views/RealProperty/details/tabs/2InventoryTab.tsx
  Code/Web/src/views/RealProperty/details/tabs/3DamageTab.tsx
  Code/Web/src/views/RealProperty/update/RealPropertyUpdate.tsx
  Code/Web/src/views/Settings/Settings.tsx
Labels: refactor, style

#43 fix(lease documents): block fetch when no tenant or no old lease sele…
  Code/Web/src/components/common/Card/Card.tsx
  Code/Web/src/components/common/Modal/Modal.tsx
  Code/Web/src/components/common/index.ts
  Code/Web/src/components/features/RealProperty/details/DetailsPart/DetailsPart.tsx
  Code/Web/src/components/features/RealProperty/details/DetailsPart/PropertyHeader.tsx
  Code/Web/src/enums/EndPointEnum.ts
  Code/Web/src/hooks/Property/useDocument.ts
  Code/Web/src/services/api/Authentification/__tests__/AuthApi.test.ts
  Code/Web/src/services/api/Owner/Properties/GetPropertyDocuments.ts
  Code/Web/src/views/RealProperty/details/tabs/1DocumentsTab.tsx
  Code/Web/src/views/RealProperty/details/tabs/2InventoryTab.tsx
Labels: docs, refactor

#47 Fix/interlacing base64 images
  Code/Mobile_Android/app/src/main/java/fr/keyz/utils/Base64Utils.kt
  Code/Mobile_Android/app/src/test/java/com/example/keyz/InventoryUnitTest.kt
Labels: bug

#49 Add missing unit tests backend
  Code/Server/controllers/dashboard_test.go
  Code/Server/router/validators/validators_test.go
  Code/Server/utils/utils_test.go
Labels: unit test

#57 fix(Room analyse + comparison): fixed no info on rooms in report
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/Managers/InventoryReportManager.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/Managers/RoomManager.swift
Labels: bug, refactor

#58 feat/ios-app - Add Document Upload/Delete Functionality & API call optimization
  Code/Mobile_iOS/Keyz/Sources/Utils/Debouncer.swift
  Code/Mobile_iOS/Keyz/Sources/Utils/ImageCache.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Overview/OverviewView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/EditPropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyDetailView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/SubViews/DocumentsGridView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/OwnerPropertyViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/TenantPropertyViewModel.swift
Labels: feature, perf, refactor

#60 iOS-app - Custom Error Alerts & Document handling optimization
  Code/Mobile_iOS/Keyz/Sources/Components/ErrorNotificationView.swift
  Code/Mobile_iOS/Keyz/Sources/Resources/en.lproj/Localizable.strings
  Code/Mobile_iOS/Keyz/Sources/Resources/fr.lproj/Localizable.strings
  Code/Mobile_iOS/Keyz/Sources/TestImmotepApp.swift
  Code/Mobile_iOS/Keyz/Sources/Utils/DocumentCache.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryStuffView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Messages/MessagesView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/CreatePropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/EditPropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/InviteTenantView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyDetailView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/SubViews/DocumentsGridView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/SubViews/ReportDamageView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/OwnerPropertyViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/TenantPropertyViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Settings/SettingsView.swift
Labels: bug, feature, perf, refactor, style

#61 Fix/ios app end lease
  Code/Mobile_iOS/Keyz/Sources/Views/Property/InviteTenantView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyDetailView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/OwnerPropertyViewModel.swift
Labels: bug, feature, refactor, style

#62 fix(login function): leaseId params is now given
  Code/Web/src/views/Authentification/Register/Register.tsx
Labels: bug

#63 Update email brevo
  Code/Server/services/brevo/brevo.go
Labels: refactor

#64 Tests/web unit tests
  Code/Web/src/components/common/Badge/__tests__/Badge.test.tsx
  Code/Web/src/components/common/Card/__tests__/Card.test.tsx
  Code/Web/src/components/common/Tag/__tests__/StatusTag.test.tsx
  Code/Web/src/views/Authentification/Login/__tests__/Login.test.tsx
Labels: unit test

#65 test (Badge): Remove useless import for the build of the application
  Code/Web/src/components/common/Badge/__tests__/Badge.test.tsx
Labels: build, deploy

#67 Update version for new release
  version.rc
Labels: deploy, ignore-for-release

#70 Doc/Web-technical doc common component
  Documentations/Technical/Web/Architecture/components/common/Badge/badge-component.md
  Documentations/Technical/Web/Architecture/components/common/Button/button-component.md
  Documentations/Technical/Web/Architecture/components/common/Card/card-component.md
  Documentations/Technical/Web/Architecture/components/common/Empty/empty-component.md
  Documentations/Technical/Web/Architecture/components/common/Input/input-component.md
  Documentations/Technical/Web/Architecture/components/common/StatusTag/status-tag-component.md
  Documentations/Technical/Web/Architecture/components/common/index.md
  Documentations/Technical/Web/Architecture/components/overview.md
  Documentations/Technical/Web/Architecture/index.md
Labels: docs, feature

#71 Rename app from Immotep to Keyz
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/mirror.yml
  Code/Server/.env.example
  Code/compose.yaml
  Documentations/Technical/Server/install.md
Labels: refactor

#73 Tenant Dashboard + Optimization in property viewmodels (owner + tenant)
  Code/Mobile_iOS/Keyz/Sources/Components/CustomAlert.swift
  Code/Mobile_iOS/Keyz/Sources/Resources/en.lproj/Localizable.strings
  Code/Mobile_iOS/Keyz/Sources/Resources/fr.lproj/Localizable.strings
  Code/Mobile_iOS/Keyz/Sources/Services/APIConfig.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryStuffView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/Managers/InventoryReportManager.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Login/LoginView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Overview/OverviewView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/CreatePropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/InviteTenantView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyDetailView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/SubViews/DamageItemView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/SubViews/DocumentsGridView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/SubViews/ReportDamageView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/TenantViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/OwnerPropertyViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/TenantPropertyViewModel.swift
Labels: bug, feature, perf, refactor, style

#74 Fix assets not copied in Dockerfile
  Code/Server/Dockerfile
  Code/Server/assets/Roboto-Bold.ttf
  Code/Server/assets/Roboto-BoldItalic.ttf
  Code/Server/assets/Roboto-Italic.ttf
  Code/Server/assets/Roboto-Regular.ttf
  Code/Server/services/pdf/pdf.go
Labels: bug

#76 Fix server unit tests
  Code/Server/services/pdf/pdf.go
Labels: bug, unit test, ignore-for-release

#75 v0.2.1
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/mirror.yml
  Code/Mobile_iOS/Keyz/Sources/Components/CustomAlert.swift
  Code/Mobile_iOS/Keyz/Sources/Components/ErrorNotificationView.swift
  Code/Mobile_iOS/Keyz/Sources/Resources/en.lproj/Localizable.strings
  Code/Mobile_iOS/Keyz/Sources/Resources/fr.lproj/Localizable.strings
  Code/Mobile_iOS/Keyz/Sources/Services/APIConfig.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryStuffView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/Managers/InventoryReportManager.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Login/LoginView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Overview/OverviewView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/CreatePropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/InviteTenantView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyDetailView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/SubViews/DamageItemView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/SubViews/DocumentsGridView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/SubViews/ReportDamageView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/TenantViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/OwnerPropertyViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/TenantPropertyViewModel.swift
  Code/Server/.env.example
  Code/Server/Dockerfile
  Code/Server/assets/Roboto-Bold.ttf
  Code/Server/assets/Roboto-BoldItalic.ttf
  Code/Server/assets/Roboto-Italic.ttf
  Code/Server/assets/Roboto-Regular.ttf
  Code/Server/services/pdf/pdf.go
  Code/compose.yaml
  Documentations/Technical/Server/install.md
  Documentations/Technical/Web/Architecture/components/common/Badge/badge-component.md
  Documentations/Technical/Web/Architecture/components/common/Button/button-component.md
  Documentations/Technical/Web/Architecture/components/common/Card/card-component.md
  Documentations/Technical/Web/Architecture/components/common/Empty/empty-component.md
  Documentations/Technical/Web/Architecture/components/common/Input/input-component.md
  Documentations/Technical/Web/Architecture/components/common/StatusTag/status-tag-component.md
  Documentations/Technical/Web/Architecture/components/common/index.md
  Documentations/Technical/Web/Architecture/components/overview.md
  Documentations/Technical/Web/Architecture/index.md
Labels: ignore-for-release
