Repository Keyz-EIP/Keyz, pull requests merged in 2025-07, with the labels that each got.

#77 Fix/ios app detailview image size
  Code/Mobile_iOS/Keyz/Sources/Components/ErrorNotificationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyDetailView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/ViewModels/OwnerPropertyViewModel.swift
Labels: bug, style

#78 Fix brevo emails wrong link to property
  Code/Server/services/brevo/brevo.go
Labels: bug

#54 Fix android forget password
  Code/Mobile_Android/.idea/deploymentTargetSelector.xml
  Code/Mobile_Android/app/src/main/java/fr/keyz/components/OpenBrowser.kt
  Code/Mobile_Android/app/src/main/java/fr/keyz/login/LoginScreen.kt
  Code/Mobile_Android/app/src/main/java/fr/keyz/realProperty/details/RealPropertyDetailsViewModel.kt
  Code/Mobile_Android/app/src/main/res/values-fr/strings.xml
  Code/Mobile_Android/app/src/main/res/values/strings.xml
Labels: bug

#81 Feat/tenant overview
  Code/Mobile_Android/app/src/main/java/fr/keyz/dashboard/DashBoard.kt
  Code/Mobile_Android/app/src/main/java/fr/keyz/dashboard/DashBoardScreenOwner.kt
  Code/Mobile_Android/app/src/main/java/fr/keyz/dashboard/tenant/TenantDashBoard.kt
  Code/Mobile_Android/app/src/main/java/fr/keyz/dashboard/tenant/TenantDashBoardViewModel.kt
  Code/Mobile_Android/app/src/main/java/fr/keyz/dashboard/widgets/Hello.kt
  Code/Mobile_Android/app/src/main/java/fr/keyz/dashboard/widgets/HelloTenant.kt
  Code/Mobile_Android/app/src/main/java/fr/keyz/dashboard/widgets/PropertyOverview.kt
  Code/Mobile_Android/app/src/main/java/fr/keyz/dashboard/widgets/WidgetBase.kt
  Code/Mobile_Android/app/src/main/res/values-fr/strings.xml
  Code/Mobile_Android/app/src/main/res/values/strings.xml
Labels: feature

#82 Fix/ios app missing translation
  Code/Mobile_iOS/Keyz/Sources/Resources/fr.lproj/Localizable.strings
  Code/Mobile_iOS/Keyz/Sources/Services/ApiService.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryRoomExitEvaluationView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/InventoryViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/Managers/FurnitureManager.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/Managers/InventoryReportManager.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Inventory/Managers/RoomManager.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Login/LoginView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Login/LoginViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Overview/OverviewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Overview/OverviewView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Overview/OverviewViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/CreatePropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/EditPropertyView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/InviteTenantView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/PropertyViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Property/TenantViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Register/RegisterView.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Register/RegisterViewModel.swift
  Code/Mobile_iOS/Keyz/Sources/Views/Settings/SettingsView.swift
Labels: bug, feature, refactor, style

#83 Feat/web accesibility
  Code/Web/src/components/features/Damages/details/DamageHeader.tsx
  Code/Web/src/components/features/Damages/details/DetailsPart.tsx
  Code/Web/src/components/features/RealProperty/PropertyCard.tsx
  Code/Web/src/components/features/RealProperty/PropertyFilterCard.tsx
  Code/Web/src/components/features/RealProperty/PropertyForm/PropertyFormFields.tsx
  Code/Web/src/components/features/RealProperty/details/DetailsPart/DetailsPart.tsx
  Code/Web/src/components/features/RealProperty/details/DetailsPart/InviteTenantModal.tsx
  Code/Web/src/components/features/RealProperty/details/DetailsPart/PropertyHeader.tsx
  Code/Web/src/components/features/RealProperty/details/DetailsPart/PropertyInfo.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Documents/DocumentList.module.css
  Code/Web/src/components/features/RealProperty/details/tabs/Documents/DocumentList.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/AddRoomModal.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/AddStuffModal.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/GridView.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/InventoryControls.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/ListView.tsx
  Code/Web/src/components/features/RealProperty/details/tabs/Inventory/PlanView.tsx
  Code/Web/src/components/features/authentication/AuthentificationPage/AuthentificationPage.tsx
  Code/Web/src/components/features/authentication/AuthentificationPage/__tests__/AuthentificationPage.test.tsx
  Code/Web/src/components/layout/DividedPage/DividedPage.tsx
  Code/Web/src/components/layout/MainLayout/MainLayout.tsx
  Code/Web/src/components/ui/PageText/Title.tsx
  Code/Web/src/index.css
  Code/Web/src/translation/locales/en.json
  Code/Web/src/translation/locales/fr.json
  Code/Web/src/views/Authentification/ForgotPassword/ForgotPassword.tsx
  Code/Web/src/views/Authentification/Login/Login.module.css
  Code/Web/src/views/Authentification/Login/Login.tsx
  Code/Web/src/views/Authentification/Register/Register.module.css
  Code/Web/src/views/Authentification/Register/Register.tsx
  Code/Web/src/views/Damages/details/DamageDetails.tsx
  Code/Web/src/views/Lost/Lost.tsx
  Code/Web/src/views/Overview/Overview.tsx
  Code/Web/src/views/RealProperty/RealProperty.tsx
  Code/Web/src/views/RealProperty/create/RealPropertyCreate.tsx
  Code/Web/src/views/RealProperty/details/RealPropertyDetails.tsx
  Code/Web/src/views/RealProperty/details/tabs/1DocumentsTab.tsx
  Code/Web/src/views/RealProperty/details/tabs/2InventoryTab.tsx
  Code/Web/src/views/RealProperty/details/tabs/3DamageTab.tsx
  Code/Web/src/views/RealProperty/update/RealPropertyUpdate.tsx
  Code/Web/src/views/Settings/Settings.module.css
  Code/Web/src/views/Settings/Settings.tsx
Labels: feature, refactor, style

#86 feat(iOS App technical doc): added all missing technical documentatio…
  Documentations/Technical/Mobile_iOS/API/API Callers/DamagesManager.md
  Documentations/Technical/Mobile_iOS/API/API Callers/DashboardManager.md
  Documentations/Technical/Mobile_iOS/API/API Callers/FurnituresManager.md
  Documentations/Technical/Mobile_iOS/API/API Callers/InventoryReportManager.md
  Documentations/Technical/Mobile_iOS/API/API Callers/InviteTenantManager.md
  Documentations/Technical/Mobile_iOS/API/API Callers/PropertiesManager.md
  Documentations/Technical/Mobile_iOS/API/API Callers/RoomsManager.md
  Documentations/Technical/Mobile_iOS/API/APIService.md
  Documentations/Technical/Mobile_iOS/API/index.md
  Documentations/Technical/Mobile_iOS/Utilities/Components/CustomAlerts.md
  Documentations/Technical/Mobile_iOS/Utilities/Components/CustomTextInputs.md
  Documentations/Technical/Mobile_iOS/Utilities/Components/NotificationView.md
  Documentations/Technical/Mobile_iOS/Utilities/Components/TopBar.md
  Documentations/Technical/Mobile_iOS/Utilities/Utils/AppDelegate.md
  Documentations/Technical/Mobile_iOS/Utilities/Utils/Bundle.md
  Documentations/Technical/Mobile_iOS/Utilities/Utils/Debouncer.md
  Documentations/Technical/Mobile_iOS/Utilities/Utils/DebugAPIRequests.md
  Documentations/Technical/Mobile_iOS/Utilities/Utils/DocumentsCache.md
  Documentations/Technical/Mobile_iOS/Utilities/Utils/FormatDate.md
  Documentations/Technical/Mobile_iOS/Utilities/Utils/ImagePicker.md
  Documentations/Technical/Mobile_iOS/Utilities/Utils/ImagesCache.md
  Documentations/Technical/Mobile_iOS/Utilities/Utils/ThemeManager.md
  Documentations/Technical/Mobile_iOS/Utilities/index.md
  Documentations/Technical/Mobile_iOS/Views/DamageDetailsView.md
  Documentations/Technical/Mobile_iOS/Views/EntryPoint.md
  Documentations/Technical/Mobile_iOS/Views/Inventory/InventoryEvaluationView.md
  Documentations/Technical/Mobile_iOS/Views/Inventory/InventoryRoomEvaluationView.md
  Documentations/Technical/Mobile_iOS/Views/Inventory/InventoryRoomView.md
  Documentations/Technical/Mobile_iOS/Views/Inventory/InventoryStuffView.md
  Documentations/Technical/Mobile_iOS/Views/InviteTenantView.md
  Documentations/Technical/Mobile_iOS/Views/Login.md
  Documentations/Technical/Mobile_iOS/Views/Overview.md
  Documentations/Technical/Mobile_iOS/Views/Property/CreatePropertyView.md
  Documentations/Technical/Mobile_iOS/Views/Property/EditPropertyView.md
  Documentations/Technical/Mobile_iOS/Views/Property/PropertyDetailView.md
  Documentations/Technical/Mobile_iOS/Views/Property/PropertyView.md
  Documentations/Technical/Mobile_iOS/Views/Register.md
  Documentations/Technical/Mobile_iOS/Views/Settings.md
  Documentations/Technical/Mobile_iOS/index.md
Labels: docs, feature
